# Generated by Django 4.1.1 on 2023-02-05 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.UUID('12356fa4-d595-4061-8ef5-f3e471205ca4'), primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='DESCRIPTION')),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED'), ('CREATED', 'CREATED')], default='CREATED', max_length=100, verbose_name='STATUS')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ('-created',),
            },
        ),
    ]
