# Generated by Django 4.1.1 on 2023-02-10 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(choices=[('FAMILY', 'FAMILY'), ('INDIVIDUAL', 'INDIVIDUAL')], default='FAMILY', max_length=100, unique=True, verbose_name='BELONG TO')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='DESCRIPTION')),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('EXPIRED', 'EXPIRED'), ('CREATED', 'CREATED')], default='CREATED', max_length=100, verbose_name='STATUS')),
                ('holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='USER')),
                ('schedule_group', models.ForeignKey(default='FAMILY', on_delete=django.db.models.deletion.PROTECT, to='django_app.scheduletype', verbose_name='GROUP')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
                'ordering': ('-created',),
            },
        ),
    ]
