# Generated by Django 4.1.1 on 2023-02-05 12:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.UUIDField(default=uuid.UUID('061448b7-0593-4d7c-9b78-7fdcedbe96fe'), primary_key=True, serialize=False),
        ),
    ]
