# Generated by Django 4.0.4 on 2022-04-20 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=10)),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.CharField(choices=[('Important', 'Important'), ('Common', 'Common')], default='Common', max_length=20)),
                ('status', models.CharField(choices=[('Done', 'Done'), ('In process', 'In process')], default='N/A', max_length=20)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='todo.tododate')),
            ],
        ),
    ]
