# Generated by Django 4.0.4 on 2022-04-20 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'ordering': ('group__date',)},
        ),
    ]
