# Generated by Django 4.0.4 on 2022-05-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_items_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_serialized', to='todo.tododate'),
        ),
    ]
